# config/settings.yml
defaults: &defaults
  color: "#7fd183,#007565,#3ac8bb,#e7417b,#a747a6,#00c8dc,#0086b4,#7fd183,#f19739,#b5ac64,#5f5f5f,#fd5000"
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
